- name: Install aptitude
  become: true
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Update aptitude
  shell:
    cmd: apt update -y

- name: Add citus repository
  shell:
    cmd: "curl https://install.citusdata.com/community/deb.sh | sudo bash"

- name: Install postgres 15 + Citus 11.2
  apt:
    pkg:
      - postgresql-15-citus-11.2
    state: latest
    update_cache: true

- name: Copy configuration files to /etc/postgresql/15/main
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ lookup('env', 'PWD') }}/artifacts/postgres-citus/pg_hba.conf", dest: "/etc/postgresql/15/main"}
    - { src: "{{ lookup('env', 'PWD') }}/artifacts/postgres-citus/postgresql.conf", dest: "/etc/postgresql/15/main"}

- name: Restart service postgresql after load new configurations
  service:
    name: postgresql
    state: restarted

- name: Enable service postgresql
  service:
    name: postgresql
    enabled: yes

- name: Add the Citus extension to every database in the cluster
  shell:
    cmd: sudo -i -u postgres psql -c "CREATE EXTENSION citus;" > /dev/null 2>&1 &

- name: Add worker node information
  shell:
    cmd: sudo -i -u postgres psql -c "SELECT citus_set_coordinator_host('10.0.0.82', 5432);" > /dev/null 2>&1 &
    
- name: Verify that installation has succeeded
  shell:
    cmd: sudo -i -u postgres psql -c "SELECT * FROM citus_get_active_worker_nodes();"